on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: ./
      with:
        host: ${{secrets.SONAR_URL}}
        login: ${{secrets.SONAR_TOKEN}}
